### PR TITLE
Adding feature to Execute the Inventory Command

### PR DESCRIPTION
**Pull request by chungeun-choi**
Hello go-ansible Contributors!

This is chung-eun, discussing the inventory-related feature (#132). Our project urgently needed this functionality, so I went ahead and developed it.

I'm eager to contribute these developments to the go-ansible project, which is why I've submitted this PR. While I've based my work on the existing contribution guidelines and source code, please don't hesitate to leave comments if there are areas for improvement! ☺️

## Inventory

- `ansibleInventoryOptions`: An object to create option flags for executing the ansible-inventory command.
- `ansibleInventoryCmd`: The object that actually executes the ansible-inventory command.
- `inventory_test.go`: A file containing test code to test the newly added features.

### Special Notes

1. As everyone knows, inventory does not involve actual server connection tasks, so `ConnectionOptions` and `PrivilegeEscalationOptions` have been excluded from the properties of `ansibleInventoryCmd`.
2. `ansibleInventoryOptions`: This functionality has been developed based on the [official ansible-inventory documentation](https://docs.ansible.com/ansible/latest/cli/ansible-inventory.html)

----

I'm not entirely sure which branch this PR should be based on, so I've made the request against the master branch for now. If it needs to be changed, please let me know.

### CODE REVIEW

**Comment by apenella** [comment]
Thank you very much for your contribution @chungeun-choi I will review it during the next few day!

**Comment by chungeun-choi** [comment]
@apenella Thank you for your reply! I'll be looking forward to your review!

**Review by apenella — CHANGES_REQUESTED** [review]
Hi @chungeun-choi !
Thank you very much for your contribution; it will be greatly appreciated by the community!

If you don't mind, before we proceed with merging, I'd like to request some additional work:
- I noticed that ansible-inventory has the '--limit' option, and it might be beneficial to include it here.
- Would you mind adding a description of that package in the readme file, specifically in the [packages](https://github.com/apenella/go-ansible?tab=readme-ov-file#packages) section?
- Lastly, could I ask you to provide an example showcasing how to use the ansible-inventory feature?

Again thank you very much for your effort and contribution!

**Comment by chungeun-choi** [comment]
@apenella Thanks for the feedback. It seems I missed a few things! I'll leave a comment again after I've made the necessary adjustments

**Comment by chungeun-choi** [comment]
@apenella HI!. I've completed all the tasks you requested and am leaving a comment. While checking, I noticed a few issues and made some modifications. Please refer to the content below!

### Requested Items

1. Addition of the [`--limit` flag functionality ](https://github.com/Okestro-Community-Dev/go-ansible/blob/990281c4558af22efaa6b5994e839c4b4b917992/pkg/inventory/inventory.go#L32)and adding test code for it.
2. Update the [README.md ](https://github.com/Okestro-Community-Dev/go-ansible/blob/feat/inventory/README.md#inventory)to include information about this feature in the packages section.
3. Add [example code](https://github.com/Okestro-Community-Dev/go-ansible/tree/feat/inventory/examples) for how to use this feature in the examples section.

### Modifications

1. `--vars` is not for inputting additional variables, but is used with the `--graph` flag to show the variable values held by each Host.
   
   -> As a result, the vaulted encryption process has been removed (related functions deleted, and this item is removed from the test code).
   
2. The placement of the 'pattern' was initially set at the end of the command, but this was causing problems in certain situations.
   
   -> The placement of the 'pattern' value has been moved to follow right after `DefaultAnsibleInventoryBinary`.
   
3. Improved an issue where certain option flags were being set to “nil”.

**Review by apenella — APPROVED** [review]

**Comment by apenella** [comment]
@chungeun-choi you did a great job with that contribution! 
Thanks so much!

**Comment by chungeun-choi** [comment]
@apenella I'm happy that what I've developed can be helpful!

**Pull request merged**
